### ISSUE TITLE
ContentPage not showing

### ISSUE THREAD

**Issue by timdmaxey** [softlion/WheelPicker-Samples#1]
Downloaded trial, when the contenpage loads, alert says to try or buy, I hit either one and the content page never loads...

So I buy it $49 and now the contentpage just doesn't load... alert box gone...

    public IList<string> wpItemsSource { get; } = new List<string>
    {
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
    };

    WheelPicker wp = new WheelPicker();
    wp.SetValue(WheelPicker.ItemsSourceSimpleProperty, wpItemsSource);

    stacklayout.Children.Add(wp);

if I debug to last line I have  WheelPicker with 7 values, just never loads the page...

**Comment by timdmaxey** [comment]
And yes this is the AppDelegate

    Vapolia.WheelPickerForms.Ios.WheelPickerRenderer.InitializeForms();
    global::Xamarin.Forms.Forms.Init();

**Comment by timdmaxey** [comment]
ok so the wheel works in a xaml test i did, so any ideas on .cs view? I'm working with an existing contentPage but it's in .cs not xaml? thanks

**Comment by softlion** [comment]
Hi Tim, please use the prerelease package on the private nuget server. It has lots of new features and do work seemlessly!

**Comment by softlion** [comment]
I suppose you also need to set a height for the control. Otherwise its height will be 0 ...

**Comment by timdmaxey** [comment]
Yeah not sure you are understanding pre-release etc is included from private git, works with xaml view, but not with .cs view... And I have height set, it's just not opening the .cs view, view just never loads... xaml view loads fine. Hoping to not have to convert someone else's .cs view to a xaml view...


WheelPicker wp = new WheelPicker();
            wp.SetValue(WheelPicker.ItemsSourceSimpleProperty, wpItemsSource);
            wp.HorizontalOptions = LayoutOptions.Fill;
            wp.HeightRequest = 150;
            wp.WidthRequest = 75;
            wp.VerticalOptions = LayoutOptions.CenterAndExpand;

.cs view never loads, so can't even see the wheelpicker...

**Comment by timdmaxey** [comment]
Assuming maybe it's because we don't have WheelDefinitions set? Will you kindly provide option for adding picker in a .cs view?

**Comment by timdmaxey** [comment]
ok all good, got it this way...

WheelDefinition wd = new WheelDefinition();
            wd.Width = 75;
            wd.HorizontalOptions = Vapolia.WheelPickerCore.WheelItemAlign.Left;
            wd.Alignment = Vapolia.WheelPickerCore.WheelItemAlign.Center;

            IList<WheelDefinition> iwds = new List<WheelDefinition>();
            iwds.Add(wd);
            wp.WheelDefinitions = iwds;


loads now, thanks
