### ISSUE TITLE
[Android] Columns not visible till interacted with (Columns Invisible)

### ISSUE THREAD

**Issue by jvhgamer** [softlion/WheelPicker-Samples#10]
Sample [repo](https://github.com/jvhgamer/WheelPickerSample)

Here is more information about my test devices:

Physical
iOS: iPhone 8
Android: Galaxy S9+

Simulators
Variety, on both platforms

In this sample, the column spacing, preset locations for each column, and visibility all work as expected on iOS. On Android, the columns are invisible till the user interacts with them. @softlion Please see sample.

**Comment by jvhgamer** [comment]
@softlion Have you viewed the sample?

**Comment by jvhgamer** [comment]
@softlion ?

**Comment by jvhgamer** [comment]
Are we missing a step in the implementation or is this package not suitable for Android @softlion ? Any response here is kindly appreciated.

**Comment by softlion** [comment]
Hi,
ty for your report.

I've checked your repro project. There is an issue in it.
Line 255 of `MainPage.cs`, `pickerViewModel.IsVisible = false;` should be `pickerViewModel.IsVisible = true;`

Also you need to specify an item template like this, and it fixes your issue:
```csharp
var textItemTemplate = new DataTemplate(() =>
{
      var template = new Label {FontSize = Device.GetNamedSize(NamedSize.Small, typeof(Label))};
      template.SetBinding(Label.TextProperty, ".");
      return template;
});

new WheelDefinition {
    ...
    ItemTemplate = textItemTemplate,
},
```

Also ther is need to switch to another control for iOS. It's the same Xamarin Forms control.
