### ISSUE TITLE
Can I Fade the shadow values for wheel picker shown in Android devices - Xamarin Forms

### ISSUE THREAD

**Issue by khadeeja-alif** [softlion/WheelPicker-Samples#11]
![7477597e-e59a-407e-b17b-6c23a44f8396](https://user-images.githubusercontent.com/14857549/57693096-0094bc00-7666-11e9-9ff0-1ff35a1d33d6.jpg)

Can I hide or disable that shadow like text from my wheel picker?
I am using Wheel Picker in Xamarin Forms.

**Comment by softlion** [comment]
There is no such "shadow" value.
Do you have a repro project ?

If you don't use an ItemTemplate in your WheelDefinition, try to use one.
Feel free to reopen.
