### ISSUE TITLE
License de communauté 

### ISSUE THREAD

**Issue by abenzakour** [softlion/WheelPicker-Samples#15]
Bonjour, 

Avez vous une License pour la communauté ?

**Comment by softlion** [comment]
Bonjour,
Oui bien sûr.

Donner moi l’ID de l’app iOS/android et le lien GitHub ou équivalent et je
vous l’email.

**Comment by abenzakour** [comment]
Parfait,

Mon App iD est   com.om.neurolight    ( Android et iOS )
L'application n'est pas partagé sur GitHub elle est en local. 

Merci beaucoup

**Comment by softlion** [comment]
> L'application n'est pas partagé sur GitHub elle est en local. 

Rebonjour, seules les apps open source sont éligibles.Elles doivent être publiés et accessibles pour validation (github, bitbucket, ...).
Même si elle n'est pas terminée, vous pouvez la publier par ex sur votre compte github avec une license MIT.

**Comment by abenzakour** [comment]
ça marche, je vais l’héberger et partager le lien

**Comment by abenzakour** [comment]
C'est fait; 
Voici le lien du projet sur Github :
https://github.com/YBENZAKOUR/Neurolight

Merci d'avance

**Comment by softlion** [comment]
Voila c'est envoyé en issue sur ton github.
Bon code !

**Comment by abenzakour** [comment]
Merci
