### ISSUE TITLE
Doesn't work? 

### ISSUE THREAD

**Issue by dentep** [softlion/WheelPicker-Samples#19]
Your sln file from repo doesn't work due to mixed assemblies (android/iOS)

when trying to follow your tutorial I get this error:

Method `Vapolia.WheelPickerForms.IntegerListTypeConverter..ctor()' is inaccessible from method `<page>.InitializeComponent()'

**Comment by softlion** [comment]
Hi dentep,
don't forget to set the correct configuration + platform on the configuration manager.

Visual Studio don't let us set one by default. It's up to you.

**Comment by vipulbuoyancy** [comment]
Hi Softlion,

Can  you please help me with what is the correct configuration and platform? 

Thanks,
Vipul

**Comment by softlion** [comment]
Use debug / iphonesimulator

**Comment by vipulbuoyancy** [comment]
I am getting this error on Android device.

**Comment by softlion** [comment]
Is it your 1st xamarin app ?

**Comment by vipulbuoyancy** [comment]
What is the price for your plugin?

**Comment by softlion** [comment]
Plz ask on vapolia.eu chat box ty !
