### ISSUE TITLE
Attribute itemTextColor already defined

### ISSUE THREAD

**Issue by mariomoramontero** [softlion/WheelPicker-Samples#4]
Hi, 
I'm trying to compile the demo but I cannot workaround this:

Error		\temp\WheelPicker-Samples-master\Demos\WheelPickerDemo.Forms\WheelPickerDemo.Forms.Android\obj\Debug\lp\4\jl\res\values\attrs.xml:1: error: Attribute "itemTextColor" has already been defined	WheelPickerDemo.Forms.Android	C:\temp\WheelPicker-Samples-master\Demos\WheelPickerDemo.Forms\WheelPickerDemo.Forms.Android\C

**Comment by softlion** [comment]
That's a Xamarin issue, not a WheelPicker issue.
