### ISSUE TITLE
Xamarin component store no longer accepting payments

### ISSUE THREAD

**Issue by gitizenme** [softlion/WheelPicker-Samples#5]
The Xamarin component store is no longer accepting payments and is migrating to NuGet. How do I purchase a license for WheelPicker?

**Comment by softlion** [comment]
Hi @gitizenme, email contact@vapolia.fr with the following informations, and we'll send you back a link with an online payment form from Stripe, or bank informations if you prefer wire transfer.

- License type: personal (tied to a developer) or enterprise (tied to an enterprise's site)
- Number of licences (one per developer)
- Your country
- If you purshase as a company, and if this company is in the E.U., its VAT number

Real online support with code/screen sharing is available through hackhands.com/benji and soon pluralsight mentoring for WheelPicker and XamSvg, but also for any Xamarin, C# or .NET Core related issue.
