### ISSUE TITLE
Prevent user action

### ISSUE THREAD

**Issue by Gonsalo** [softlion/WheelPicker-Samples#7]
Hi there,

I'm building a simple android app and I'm using this package to display/edit dates. On display mode the user should be prevented from moving the wheel, hence my issue, I need to prevent the users from moving the wheel in certain cases.

Once this passes the tests I will proceed to purchase the package :)

Thanks.

**Comment by softlion** [comment]
On display mode, hide the control and display a text with the date. Displaying a "read only wheel" is a bad ui, as your customer will feel bad as he sees a wheel but can not move it.
