### ISSUE TITLE
System.TypeLoadException has been thrown

### ISSUE THREAD

**Issue by mycybersiara** [softlion/WheelPicker-Samples#8]
System.TypeLoadException
VTable setup of type Vapolia.WheelPickerForms.Droid.WheelPickerRenderer failed 

in andorid

xamarin.forms - 3.4.xxx
vapolia.wheelpicker - 2.0.1

Project Target framework : .netstandard 2.0

**Comment by softlion** [comment]
Do you have a repro project plz?

**Comment by mycybersiara** [comment]
> Do you have a repro project plz?

not sure

**Comment by mycybersiara** [comment]
please give me some hint on this

**Comment by softlion** [comment]
update xamarin/vs tools. Provide a repro project

**Comment by jvhgamer** [comment]
Same issue. On XF v3.4.0.1008975. Tried updating to XF 3.6.0.264807 (latest stable) but this generated a host of anomalous errors related to Xamarin.Android. Reverted back to 3.4.0.xx. Any solutions?

**Comment by jvhgamer** [comment]
Updating Xamarin.Forms pkg fixed, for me.

**Comment by mycybersiara** [comment]
in Project Target framework : .netstandard 2.0?
@jvhgamer

**Comment by softlion** [comment]
nice you fixed it alone.
