### ISSUE TITLE
[ANDROID] Columns invisible

### ISSUE THREAD

**Issue by jvhgamer** [softlion/WheelPicker-Samples#9]
`Columns` in `WheelPicker` do not show items till interacted with. Swiping up or swiping down, the items for that column appear.

Note1: Do not have a physical `Android` device to test with. Encountered on `Android` emulator/sim.
Note2: Not encountered on `iOS` as `WheelPicker` class used is `WheelPickerModel : UIPickerViewModel`

**Comment by jvhgamer** [comment]
Updates or news on this @softlion ?

**Comment by jvhgamer** [comment]
Updates or news on this @softlion ?

**Comment by jvhgamer** [comment]
If it's any help, the wheel isn't showing any items at all in any columns. Once a column is interacted with , the items show.

**Comment by jvhgamer** [comment]
Bump

**Comment by jvhgamer** [comment]
BUMP

**Comment by jvhgamer** [comment]
This package is unusable on Android. Can provide sample via a github repo project if it would help. Any response @softlion is greatly appreciated.

**Comment by softlion** [comment]
Just tried on both simulator and device, it works fine. Until you provide more informations about your test devices, i close your issue.
